import AppProvider from "@/components/AppProvider";
import Header from "@/components/Header";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "@ant-design/v5-patch-for-react-19";
import type { Metadata } from "next";
import "../assets/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <AntdRegistry>
        <body>
          <AppProvider>
            <Header />
            <main className="container mx-auto px-4 min-h-screen">
              {children}
            </main>
          </AppProvider>
        </body>
      </AntdRegistry>
    </html>
  );
}
